"""Migración inicial

Revision ID: 9d49f7e7d8f3
Revises: 91e483bf9988
Create Date: 2023-10-12 13:01:57.800204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d49f7e7d8f3'
down_revision: Union[str, None] = '91e483bf9988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
